[build]
  # Directory to change to before starting a build
  base = "vedanta-vision_-the-sage-ai"

  # Directory that contains the deploy-ready HTML files and assets
  publish = "vedanta-vision_-the-sage-ai/dist"

  # Default build command
  command = "npm run build"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # NPM version
  NPM_VERSION = "9"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for API routes (if any)
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Environment variables (these should be set in Netlify dashboard)
# VITE_CLERK_PUBLISHABLE_KEY
# VITE_GEMINI_API_KEY
# VITE_GROQ_API_KEY
# VITE_OPENROUTER_API_KEY

# Form handling (if needed for contact forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Functions (for serverless functions if needed)
[functions]
  directory = "netlify/functions"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 5731
  publish = "dist"
  autoLaunch = false
